name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2
  ECR_REPOSITORY: kizzuato/desaconnect
  ECS_SERVICE: task-ets2-service-7023invc
  ECS_CLUSTER: Cluster-Pengaduan
  # Gunakan NAMA Task Definition (bukan path file) untuk didownload otomatis
  ECS_TASK_DEFINITION_NAME: task-ets2 
  # SESUAIKAN: Di screenshot kamu namanya 'ets2', bukan 'desaconnect-app'
  CONTAINER_NAME: ets2 

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Kode Repositori
      uses: actions/checkout@v4 # Update ke v4 biar gak warning

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4 # Update ke v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login ke Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, dan push image Docker ke Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    # LANGKAH KUNCI: Download spek asli dari AWS biar gak ada salah nama container
    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION_NAME }} --query taskDefinition > task-definition.json

    - name: Sisipkan Image ID baru ke dalam Amazon ECS Task Definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Task Definition baru ke Amazon ECS Fargate
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
